// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc/CommonService.proto

package xblog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CommonResponse) Validate() error {
	return nil
}

var _regex_RegisterRequest_Email = regexp.MustCompile(`^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(.[a-zA-Z0-9_-]+)+$`)

func (this *RegisterRequest) Validate() error {
	if !_regex_RegisterRequest_Email.MatchString(this.Email) {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(.[a-zA-Z0-9_-]+)+$"`, this.Email))
	}
	if !(len(this.Username) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Username))
	}
	if !(len(this.Username) < 21) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length smaller than '21'`, this.Username))
	}
	if !(len(this.Password) > 7) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length greater than '7'`, this.Password))
	}
	if !(len(this.Password) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.Password))
	}
	if !(len(this.PasswordConfirmed) > 7) {
		return github_com_mwitkow_go_proto_validators.FieldError("PasswordConfirmed", fmt.Errorf(`value '%v' must have a length greater than '7'`, this.PasswordConfirmed))
	}
	if !(len(this.PasswordConfirmed) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("PasswordConfirmed", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.PasswordConfirmed))
	}
	return nil
}
func (this *RegisterResponse) Validate() error {
	return nil
}
func (this *LoginRequest) Validate() error {
	return nil
}
func (this *LoginResponse) Validate() error {
	if this.UserInfo != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserInfo); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserInfo", err)
		}
	}
	return nil
}
func (this *CreatePostRequest) Validate() error {
	if !(this.AuthorId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("AuthorId", fmt.Errorf(`value '%v' must be greater than '0'`, this.AuthorId))
	}
	if !(len(this.Title) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Title))
	}
	if !(len(this.Title) < 200) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length smaller than '200'`, this.Title))
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *CreatePostResponse) Validate() error {
	return nil
}
func (this *UpdatePostRequest) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	if !(len(this.Title) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Title))
	}
	if !(len(this.Title) < 200) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length smaller than '200'`, this.Title))
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *PostListRequest) Validate() error {
	return nil
}
func (this *PostListResponse) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *DeletePostRequest) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	return nil
}
func (this *PostDetail) Validate() error {
	if this.Author != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Author); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Author", err)
		}
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *User) Validate() error {
	return nil
}
func (this *Tag) Validate() error {
	return nil
}
