// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/CommonService.proto

package xblog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//common message
type CommonResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type RegisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type LoginRequest struct {
	Username             int32    `protobuf:"varint,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() int32 {
	if m != nil {
		return m.Username
	}
	return 0
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CreatePostRequest struct {
	AuthorId             uint32   `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CategoryId           int32    `protobuf:"varint,7,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`
	TagArray             []*Tag   `protobuf:"bytes,8,rep,name=TagArray,proto3" json:"TagArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{5}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetAuthorId() uint32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *CreatePostRequest) GetTagArray() []*Tag {
	if m != nil {
		return m.TagArray
	}
	return nil
}

type CreatePostResponse struct {
	PostId               uint32   `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{6}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type UpdatePostRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CategoryId           int32    `protobuf:"varint,7,opt,name=CategoryId,proto3" json:"CategoryId,omitempty"`
	TagArray             []*Tag   `protobuf:"bytes,8,rep,name=TagArray,proto3" json:"TagArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{7}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostRequest) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *UpdatePostRequest) GetTagArray() []*Tag {
	if m != nil {
		return m.TagArray
	}
	return nil
}

type PostListRequest struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostListRequest) Reset()         { *m = PostListRequest{} }
func (m *PostListRequest) String() string { return proto.CompactTextString(m) }
func (*PostListRequest) ProtoMessage()    {}
func (*PostListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{8}
}

func (m *PostListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostListRequest.Unmarshal(m, b)
}
func (m *PostListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostListRequest.Marshal(b, m, deterministic)
}
func (m *PostListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostListRequest.Merge(m, src)
}
func (m *PostListRequest) XXX_Size() int {
	return xxx_messageInfo_PostListRequest.Size(m)
}
func (m *PostListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostListRequest proto.InternalMessageInfo

func (m *PostListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PostListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type PostListResponse struct {
	Count                uint32        `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Page                 uint32        `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	List                 []*PostDetail `protobuf:"bytes,3,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostListResponse) Reset()         { *m = PostListResponse{} }
func (m *PostListResponse) String() string { return proto.CompactTextString(m) }
func (*PostListResponse) ProtoMessage()    {}
func (*PostListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{9}
}

func (m *PostListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostListResponse.Unmarshal(m, b)
}
func (m *PostListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostListResponse.Marshal(b, m, deterministic)
}
func (m *PostListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostListResponse.Merge(m, src)
}
func (m *PostListResponse) XXX_Size() int {
	return xxx_messageInfo_PostListResponse.Size(m)
}
func (m *PostListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostListResponse proto.InternalMessageInfo

func (m *PostListResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PostListResponse) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PostListResponse) GetList() []*PostDetail {
	if m != nil {
		return m.List
	}
	return nil
}

type PostDetail struct {
	Id     uint32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Author *Author `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Title  string  `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	// Types that are valid to be assigned to ContentOrDigest:
	//	*PostDetail_Digest
	//	*PostDetail_Content
	ContentOrDigest      isPostDetail_ContentOrDigest `protobuf_oneof:"ContentOrDigest"`
	TagArray             []*Tag                       `protobuf:"bytes,8,rep,name=TagArray,proto3" json:"TagArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PostDetail) Reset()         { *m = PostDetail{} }
func (m *PostDetail) String() string { return proto.CompactTextString(m) }
func (*PostDetail) ProtoMessage()    {}
func (*PostDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{10}
}

func (m *PostDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDetail.Unmarshal(m, b)
}
func (m *PostDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDetail.Marshal(b, m, deterministic)
}
func (m *PostDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDetail.Merge(m, src)
}
func (m *PostDetail) XXX_Size() int {
	return xxx_messageInfo_PostDetail.Size(m)
}
func (m *PostDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PostDetail proto.InternalMessageInfo

func (m *PostDetail) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PostDetail) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PostDetail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type isPostDetail_ContentOrDigest interface {
	isPostDetail_ContentOrDigest()
}

type PostDetail_Digest struct {
	Digest string `protobuf:"bytes,4,opt,name=Digest,proto3,oneof"`
}

type PostDetail_Content struct {
	Content string `protobuf:"bytes,5,opt,name=Content,proto3,oneof"`
}

func (*PostDetail_Digest) isPostDetail_ContentOrDigest() {}

func (*PostDetail_Content) isPostDetail_ContentOrDigest() {}

func (m *PostDetail) GetContentOrDigest() isPostDetail_ContentOrDigest {
	if m != nil {
		return m.ContentOrDigest
	}
	return nil
}

func (m *PostDetail) GetDigest() string {
	if x, ok := m.GetContentOrDigest().(*PostDetail_Digest); ok {
		return x.Digest
	}
	return ""
}

func (m *PostDetail) GetContent() string {
	if x, ok := m.GetContentOrDigest().(*PostDetail_Content); ok {
		return x.Content
	}
	return ""
}

func (m *PostDetail) GetTagArray() []*Tag {
	if m != nil {
		return m.TagArray
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PostDetail) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PostDetail_Digest)(nil),
		(*PostDetail_Content)(nil),
	}
}

type Author struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{11}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Author) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type Tag struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=Alias,proto3" json:"Alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_78bb15a4fe2cd657, []int{12}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonResponse)(nil), "xblog.CommonResponse")
	proto.RegisterType((*RegisterRequest)(nil), "xblog.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "xblog.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "xblog.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "xblog.LoginResponse")
	proto.RegisterType((*CreatePostRequest)(nil), "xblog.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "xblog.CreatePostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "xblog.UpdatePostRequest")
	proto.RegisterType((*PostListRequest)(nil), "xblog.PostListRequest")
	proto.RegisterType((*PostListResponse)(nil), "xblog.PostListResponse")
	proto.RegisterType((*PostDetail)(nil), "xblog.PostDetail")
	proto.RegisterType((*Author)(nil), "xblog.Author")
	proto.RegisterType((*Tag)(nil), "xblog.Tag")
}

func init() { proto.RegisterFile("rpc/CommonService.proto", fileDescriptor_78bb15a4fe2cd657) }

var fileDescriptor_78bb15a4fe2cd657 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x49, 0x9c, 0xb8, 0x43, 0x03, 0x64, 0x4b, 0xc1, 0xf5, 0x05, 0xd7, 0x2a, 0x34, 0x87,
	0x92, 0x48, 0xa9, 0xd4, 0x0b, 0xaa, 0xaa, 0x24, 0xa8, 0x02, 0x09, 0x51, 0xb4, 0x0d, 0xb7, 0x5e,
	0x96, 0x64, 0x65, 0x56, 0x24, 0x5e, 0x77, 0xbd, 0xe1, 0xe7, 0xda, 0x47, 0xeb, 0xa9, 0xe2, 0xd0,
	0x57, 0x40, 0xe2, 0x49, 0x2a, 0xef, 0xae, 0x7f, 0x20, 0x48, 0xed, 0xb1, 0x37, 0x7f, 0xf3, 0xf3,
	0x79, 0xbe, 0x99, 0x9d, 0x81, 0x4d, 0x11, 0x8f, 0xbb, 0x43, 0x3e, 0x9b, 0xf1, 0xe8, 0x2b, 0x15,
	0x97, 0x6c, 0x4c, 0x3b, 0xb1, 0xe0, 0x92, 0x23, 0xfb, 0xfa, 0x6c, 0xca, 0x43, 0xef, 0x43, 0xc8,
	0xe4, 0xf9, 0xfc, 0xac, 0x33, 0xe6, 0xb3, 0xee, 0xec, 0x8a, 0xc9, 0x0b, 0x7e, 0xd5, 0x0d, 0xf9,
	0xae, 0x8a, 0xd9, 0xbd, 0x24, 0x53, 0x36, 0x21, 0x92, 0x8b, 0xa4, 0x9b, 0x7f, 0xea, 0xf4, 0xa0,
	0x0d, 0x2b, 0x9a, 0x15, 0xd3, 0x24, 0xe6, 0x51, 0x42, 0xd1, 0x06, 0xd4, 0x05, 0x4d, 0xe6, 0x53,
	0xe9, 0x5a, 0xbe, 0xd5, 0xb6, 0xb1, 0x41, 0x41, 0x0b, 0x56, 0x31, 0x0d, 0x59, 0x22, 0xa9, 0xc0,
	0xf4, 0xfb, 0x9c, 0x26, 0x32, 0x40, 0xb0, 0x56, 0x98, 0x74, 0x7a, 0xf0, 0x19, 0x9e, 0x1f, 0xf1,
	0x90, 0x45, 0x26, 0x06, 0x79, 0xe0, 0xcc, 0x13, 0x2a, 0x22, 0x32, 0xa3, 0x86, 0x30, 0xc7, 0xa9,
	0x2f, 0x26, 0x49, 0x72, 0xc5, 0xc5, 0xc4, 0xad, 0xf8, 0x56, 0xfb, 0x19, 0xce, 0x71, 0xf0, 0x16,
	0x9a, 0x86, 0xe7, 0x2f, 0x75, 0xfd, 0xb6, 0xa0, 0x35, 0x14, 0x94, 0x48, 0x7a, 0xc2, 0x13, 0x99,
	0xfd, 0xf6, 0x0d, 0x38, 0xfd, 0xb9, 0x3c, 0xe7, 0xe2, 0x50, 0x53, 0x37, 0x07, 0xce, 0xfd, 0xdd,
	0x56, 0x6d, 0xcd, 0xf2, 0x2d, 0x9c, 0x7b, 0xd0, 0x6b, 0xb0, 0x47, 0x4c, 0x4e, 0xa9, 0x5b, 0x4d,
	0xff, 0x3e, 0x58, 0xbe, 0xbf, 0xdb, 0x6a, 0xf8, 0x56, 0x5c, 0xbd, 0xfe, 0x65, 0x61, 0xed, 0x41,
	0x3e, 0x34, 0x86, 0x3c, 0x92, 0x34, 0x92, 0xae, 0xad, 0x82, 0xea, 0xf7, 0x77, 0x5b, 0x15, 0xdf,
	0xc2, 0x99, 0x19, 0xed, 0x00, 0x0c, 0x89, 0xa4, 0x21, 0x17, 0x37, 0x87, 0x13, 0xb7, 0x91, 0x16,
	0x97, 0x07, 0x95, 0x3c, 0x68, 0x07, 0x9c, 0x11, 0x09, 0xfb, 0x42, 0x90, 0x1b, 0xd7, 0xf1, 0xab,
	0xed, 0xe5, 0x1e, 0x74, 0xd4, 0xf0, 0x3a, 0x23, 0x12, 0xe2, 0xdc, 0x17, 0xbc, 0x03, 0x54, 0xd6,
	0x53, 0xc8, 0x4f, 0xf1, 0xe1, 0x44, 0xc9, 0x6f, 0x62, 0x83, 0x82, 0x9f, 0x16, 0xb4, 0x4e, 0xe3,
	0xc9, 0x23, 0xf9, 0x2e, 0x54, 0xb2, 0xc8, 0x92, 0xf0, 0xca, 0xff, 0x2a, 0x79, 0x0f, 0x56, 0xd3,
	0xea, 0x8f, 0x58, 0xa1, 0x60, 0x1d, 0xec, 0x23, 0x36, 0x63, 0xd2, 0xc8, 0xd5, 0x00, 0x21, 0xa8,
	0x9d, 0x90, 0x90, 0xea, 0x91, 0x62, 0xf5, 0x1d, 0x8c, 0x61, 0xad, 0x48, 0x36, 0xdd, 0x5a, 0x07,
	0x7b, 0xc8, 0xe7, 0x51, 0x9e, 0xad, 0xc0, 0x53, 0xd9, 0x68, 0x1b, 0x6a, 0x69, 0xa6, 0x5b, 0x55,
	0xe5, 0xb5, 0x4c, 0x79, 0x29, 0xe1, 0x3e, 0x95, 0x84, 0x4d, 0xb1, 0x72, 0x07, 0xb7, 0x16, 0x40,
	0x61, 0x44, 0x2b, 0x45, 0x7f, 0x55, 0x57, 0xb7, 0xa1, 0xae, 0x1f, 0x95, 0xe2, 0x5e, 0xee, 0x35,
	0x0d, 0x8f, 0x36, 0x62, 0xe3, 0x4c, 0xcb, 0x2a, 0x35, 0x3f, 0xeb, 0xb7, 0x0b, 0xf5, 0x7d, 0x16,
	0xd2, 0x44, 0xba, 0xb5, 0xd4, 0x7c, 0xb0, 0x84, 0x0d, 0x46, 0xde, 0xa3, 0x49, 0x1c, 0x2c, 0x95,
	0x67, 0xf0, 0x4f, 0xbd, 0x1d, 0xb4, 0x60, 0xd5, 0xa4, 0x7c, 0x11, 0x9a, 0x36, 0x38, 0xc9, 0xaa,
	0x5d, 0xd0, 0xe1, 0x81, 0x73, 0x9a, 0x6d, 0xab, 0xd9, 0xc8, 0xd3, 0xd2, 0xb6, 0x1e, 0xb3, 0xf1,
	0x85, 0xf2, 0xe9, 0xfa, 0x73, 0x1c, 0x7c, 0x82, 0xea, 0x88, 0x84, 0x0b, 0x74, 0x08, 0x6a, 0xc7,
	0x05, 0x95, 0xfa, 0x4e, 0x7b, 0xd0, 0x9f, 0x32, 0x92, 0x64, 0x3d, 0x50, 0xa0, 0xf7, 0xa3, 0x02,
	0xcd, 0x07, 0xe7, 0x0d, 0xf5, 0xc0, 0x56, 0x07, 0x00, 0xbd, 0x30, 0xb2, 0xca, 0x67, 0xc5, 0x5b,
	0x7f, 0x68, 0x34, 0x63, 0xef, 0x03, 0x14, 0xab, 0x83, 0x5c, 0x13, 0xb3, 0x70, 0x1d, 0xbc, 0x57,
	0x4f, 0x78, 0x0c, 0xc5, 0x47, 0x80, 0x62, 0x9d, 0x72, 0x8a, 0x85, 0x0d, 0xf3, 0x5e, 0x66, 0x14,
	0x0f, 0xaf, 0xe7, 0x1e, 0x38, 0xd9, 0x63, 0x44, 0x1b, 0xa5, 0xc7, 0x54, 0x7a, 0xda, 0xde, 0xe6,
	0x82, 0x5d, 0x27, 0x0f, 0xe0, 0xb6, 0xd2, 0xe8, 0xc7, 0xf1, 0x37, 0x1c, 0x8f, 0xcf, 0xea, 0xea,
	0x3e, 0xbf, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x76, 0xb2, 0x7d, 0xeb, 0xf9, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonServiceClient interface {
	//注册
	//    rpc register (RegisterRequest) returns (RegisterResponse);
	//登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	//创建文章
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	//修改文章
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	//文章列表
	PostList(ctx context.Context, in *PostListRequest, opts ...grpc.CallOption) (*PostListResponse, error)
}

type commonServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommonServiceClient(cc *grpc.ClientConn) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/xblog.CommonService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/xblog.CommonService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/xblog.CommonService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) PostList(ctx context.Context, in *PostListRequest, opts ...grpc.CallOption) (*PostListResponse, error) {
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, "/xblog.CommonService/PostList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
type CommonServiceServer interface {
	//注册
	//    rpc register (RegisterRequest) returns (RegisterResponse);
	//登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	//创建文章
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	//修改文章
	UpdatePost(context.Context, *UpdatePostRequest) (*CommonResponse, error)
	//文章列表
	PostList(context.Context, *PostListRequest) (*PostListResponse, error)
}

// UnimplementedCommonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommonServiceServer struct {
}

func (*UnimplementedCommonServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedCommonServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedCommonServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedCommonServiceServer) PostList(ctx context.Context, req *PostListRequest) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostList not implemented")
}

func RegisterCommonServiceServer(s *grpc.Server, srv CommonServiceServer) {
	s.RegisterService(&_CommonService_serviceDesc, srv)
}

func _CommonService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xblog.CommonService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xblog.CommonService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xblog.CommonService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_PostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).PostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xblog.CommonService/PostList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).PostList(ctx, req.(*PostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xblog.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _CommonService_Login_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _CommonService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _CommonService_UpdatePost_Handler,
		},
		{
			MethodName: "PostList",
			Handler:    _CommonService_PostList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/CommonService.proto",
}
