// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc/CommonService.proto

package xblog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CommonResponse) Validate() error {
	return nil
}
func (this *RegisterRequest) Validate() error {
	return nil
}
func (this *RegisterResponse) Validate() error {
	return nil
}
func (this *LoginRequest) Validate() error {
	return nil
}
func (this *LoginResponse) Validate() error {
	return nil
}
func (this *CreatePostRequest) Validate() error {
	if !(this.AuthorId > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("AuthorId", fmt.Errorf(`value '%v' must be greater than '1'`, this.AuthorId))
	}
	if !(len(this.Title) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Title))
	}
	if !(len(this.Title) < 200) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length smaller than '200'`, this.Title))
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *CreatePostResponse) Validate() error {
	return nil
}
func (this *UpdatePostRequest) Validate() error {
	if !(this.Id > 1) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '1'`, this.Id))
	}
	if !(len(this.Title) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Title))
	}
	if !(len(this.Title) < 200) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length smaller than '200'`, this.Title))
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *PostListRequest) Validate() error {
	return nil
}
func (this *PostListResponse) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *PostDetail) Validate() error {
	if this.Author != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Author); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Author", err)
		}
	}
	for _, item := range this.TagArray {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TagArray", err)
			}
		}
	}
	return nil
}
func (this *Author) Validate() error {
	return nil
}
func (this *Tag) Validate() error {
	return nil
}
